# Generated by Django 5.1.1 on 2025-09-07 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_helpful_count'),
        ('store', '0010_alter_product_category_delete_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='verified_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='one_review_per_user_per_product'),
        ),
    ]
