# Generated by Django 5.1.1 on 2025-09-08 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_status'),
        ('store', '0010_alter_product_category_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product'),
        ),
    ]
